РК1 Задача, Балякин Д.В.
java-park-mail-ru/rk1_cases pull request #3
Opened 2017-03-25 21:47 UTC by Pacman29

Поправил GenericAdventure

2017-03-25 22:51 UTC, KSolovyev requested changes

2017-03-25 22:51 UTC, KSolovyev commented on GenericAdventure.java
> +        public void cry(){}
Крестьянин не может делать боевой клич. Он слишком слаб для этого

2017-03-25 22:54 UTC, KSolovyev requested changes

2017-03-25 22:54 UTC, KSolovyev commented on GenericAdventure.java
> +        void move();
Если любой человек сможет ходить, то вся армия разбежится. Этого метода тоже не должно быть здесь

2017-03-25 22:54 UTC, KSolovyev commented on GenericAdventure.java
> +    public static void moveSomething(Army army) {
Использование Raw generics это устаревший прием, ведущий к многим проблемам с типами

2017-03-26 10:32 UTC, KSolovyev requested changes

2017-03-26 10:32 UTC, KSolovyev commented on GenericAdventure.java
> +        public void move(){}
А зачем здесь этот метод, если он не используется?

2017-03-26 10:52 UTC, Pacman29 commented on GenericAdventure.java
> +        public void move(){}
Да, от прошлой реализации остался, не заметил

2017-03-26 11:15 UTC, KSolovyev commented
Хорошо, зачет

2017-03-26 11:15 UTC, closed without merging