fixed
java-park-mail-ru/rk1_cases pull request #5
Opened 2017-05-26 17:15 UTC by wolf1996

2017-05-26 18:15 UTC, KSolovyev requested changes

2017-05-26 18:15 UTC, KSolovyev commented on BoxingPuzzle.java
>              System.out.println("debug: Only half is left");
это не будет выведено

2017-05-26 20:19 UTC, wolf1996 commented on BoxingPuzzle.java
>              System.out.println("debug: Only half is left");
"debug: Only half is left" - вывелось

2017-05-26 20:19 UTC, wolf1996 commented on BoxingPuzzle.java
>              System.out.println("debug: Only half is left");
![image](https://cloud.githubusercontent.com/assets/5901874/26511228/c738d450-4269-11e7-8fc1-75aced777874.png)

2017-05-30 09:27 UTC, KSolovyev requested changes

2017-05-30 09:27 UTC, KSolovyev commented on BoxingPuzzle.java
>              System.out.println("debug: Only half is left");
тут вам повезло. Оказывается  обертки типов в промежутке от -127 до 128 интернируются. Те ведут себя как строки. https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.1.7
Для больших чисел такое не сработает, можете проверить для n = 140 и half = 137

2017-06-01 16:16 UTC, wolf1996 commented on BoxingPuzzle.java
>              System.out.println("debug: Only half is left");
Fixed 2

2017-06-01 22:40 UTC, KSolovyev commented
ok

2017-06-01 22:40 UTC, closed without merging

2017-06-01 22:40 UTC, KSolovyev commented
Напишите мне в слак, пожалуйста